// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: middlewares/proto/health.proto

package healthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_middlewares_proto_health_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_middlewares_proto_health_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_middlewares_proto_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middlewares_proto_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.health.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_middlewares_proto_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_middlewares_proto_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type SystemMetricsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeDisk    bool                   `protobuf:"varint,1,opt,name=include_disk,json=includeDisk,proto3" json:"include_disk,omitempty"`
	IncludeNetwork bool                   `protobuf:"varint,2,opt,name=include_network,json=includeNetwork,proto3" json:"include_network,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemMetricsRequest) Reset() {
	*x = SystemMetricsRequest{}
	mi := &file_middlewares_proto_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetricsRequest) ProtoMessage() {}

func (x *SystemMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_middlewares_proto_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetricsRequest.ProtoReflect.Descriptor instead.
func (*SystemMetricsRequest) Descriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{2}
}

func (x *SystemMetricsRequest) GetIncludeDisk() bool {
	if x != nil {
		return x.IncludeDisk
	}
	return false
}

func (x *SystemMetricsRequest) GetIncludeNetwork() bool {
	if x != nil {
		return x.IncludeNetwork
	}
	return false
}

type DiskUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TotalMb       uint64                 `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	UsedMb        uint64                 `protobuf:"varint,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	UsagePercent  float64                `protobuf:"fixed64,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_middlewares_proto_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_middlewares_proto_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{3}
}

func (x *DiskUsage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskUsage) GetTotalMb() uint64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *DiskUsage) GetUsedMb() uint64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *DiskUsage) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type DBStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxOpenConns  int32                  `protobuf:"varint,1,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	OpenConns     int32                  `protobuf:"varint,2,opt,name=open_conns,json=openConns,proto3" json:"open_conns,omitempty"`
	InUse         int32                  `protobuf:"varint,3,opt,name=in_use,json=inUse,proto3" json:"in_use,omitempty"`
	Idle          int32                  `protobuf:"varint,4,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBStats) Reset() {
	*x = DBStats{}
	mi := &file_middlewares_proto_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBStats) ProtoMessage() {}

func (x *DBStats) ProtoReflect() protoreflect.Message {
	mi := &file_middlewares_proto_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBStats.ProtoReflect.Descriptor instead.
func (*DBStats) Descriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{4}
}

func (x *DBStats) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *DBStats) GetOpenConns() int32 {
	if x != nil {
		return x.OpenConns
	}
	return 0
}

func (x *DBStats) GetInUse() int32 {
	if x != nil {
		return x.InUse
	}
	return 0
}

func (x *DBStats) GetIdle() int32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type ApiMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests      int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors        int64                  `protobuf:"varint,2,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"`
	ErrorRatePercent   string                 `protobuf:"bytes,3,opt,name=error_rate_percent,json=errorRatePercent,proto3" json:"error_rate_percent,omitempty"`
	SuccessRatePercent string                 `protobuf:"bytes,4,opt,name=success_rate_percent,json=successRatePercent,proto3" json:"success_rate_percent,omitempty"`
	AvgResponseTimeMs  float64                `protobuf:"fixed64,5,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	RequestsByMethod   map[string]int64       `protobuf:"bytes,6,rep,name=requests_by_method,json=requestsByMethod,proto3" json:"requests_by_method,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApiMetrics) Reset() {
	*x = ApiMetrics{}
	mi := &file_middlewares_proto_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiMetrics) ProtoMessage() {}

func (x *ApiMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_middlewares_proto_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiMetrics.ProtoReflect.Descriptor instead.
func (*ApiMetrics) Descriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{5}
}

func (x *ApiMetrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *ApiMetrics) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *ApiMetrics) GetErrorRatePercent() string {
	if x != nil {
		return x.ErrorRatePercent
	}
	return ""
}

func (x *ApiMetrics) GetSuccessRatePercent() string {
	if x != nil {
		return x.SuccessRatePercent
	}
	return ""
}

func (x *ApiMetrics) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *ApiMetrics) GetRequestsByMethod() map[string]int64 {
	if x != nil {
		return x.RequestsByMethod
	}
	return nil
}

type SystemMetricsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SystemUptimeSecs      uint64                 `protobuf:"varint,1,opt,name=system_uptime_secs,json=systemUptimeSecs,proto3" json:"system_uptime_secs,omitempty"`
	CpuUsagePercent       float64                `protobuf:"fixed64,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RamTotalMb            uint64                 `protobuf:"varint,3,opt,name=ram_total_mb,json=ramTotalMb,proto3" json:"ram_total_mb,omitempty"`
	RamUsedMb             uint64                 `protobuf:"varint,4,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`
	RamUsagePercent       float64                `protobuf:"fixed64,5,opt,name=ram_usage_percent,json=ramUsagePercent,proto3" json:"ram_usage_percent,omitempty"`
	NetBytesReceivedTotal uint64                 `protobuf:"varint,6,opt,name=net_bytes_received_total,json=netBytesReceivedTotal,proto3" json:"net_bytes_received_total,omitempty"`
	NetBytesSentTotal     uint64                 `protobuf:"varint,7,opt,name=net_bytes_sent_total,json=netBytesSentTotal,proto3" json:"net_bytes_sent_total,omitempty"`
	DiskUsages            []*DiskUsage           `protobuf:"bytes,8,rep,name=disk_usages,json=diskUsages,proto3" json:"disk_usages,omitempty"`
	ActiveWebsockets      int32                  `protobuf:"varint,9,opt,name=active_websockets,json=activeWebsockets,proto3" json:"active_websockets,omitempty"`
	GoroutineCount        int32                  `protobuf:"varint,10,opt,name=goroutine_count,json=goroutineCount,proto3" json:"goroutine_count,omitempty"`
	DbStats               *DBStats               `protobuf:"bytes,11,opt,name=db_stats,json=dbStats,proto3" json:"db_stats,omitempty"`
	AppUptime             string                 `protobuf:"bytes,12,opt,name=app_uptime,json=appUptime,proto3" json:"app_uptime,omitempty"`
	Timestamp             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CacheAge              *durationpb.Duration   `protobuf:"bytes,14,opt,name=cache_age,json=cacheAge,proto3" json:"cache_age,omitempty"`
	ApiMetrics            *ApiMetrics            `protobuf:"bytes,15,opt,name=api_metrics,json=apiMetrics,proto3" json:"api_metrics,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SystemMetricsResponse) Reset() {
	*x = SystemMetricsResponse{}
	mi := &file_middlewares_proto_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetricsResponse) ProtoMessage() {}

func (x *SystemMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_middlewares_proto_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetricsResponse.ProtoReflect.Descriptor instead.
func (*SystemMetricsResponse) Descriptor() ([]byte, []int) {
	return file_middlewares_proto_health_proto_rawDescGZIP(), []int{6}
}

func (x *SystemMetricsResponse) GetSystemUptimeSecs() uint64 {
	if x != nil {
		return x.SystemUptimeSecs
	}
	return 0
}

func (x *SystemMetricsResponse) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemMetricsResponse) GetRamTotalMb() uint64 {
	if x != nil {
		return x.RamTotalMb
	}
	return 0
}

func (x *SystemMetricsResponse) GetRamUsedMb() uint64 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *SystemMetricsResponse) GetRamUsagePercent() float64 {
	if x != nil {
		return x.RamUsagePercent
	}
	return 0
}

func (x *SystemMetricsResponse) GetNetBytesReceivedTotal() uint64 {
	if x != nil {
		return x.NetBytesReceivedTotal
	}
	return 0
}

func (x *SystemMetricsResponse) GetNetBytesSentTotal() uint64 {
	if x != nil {
		return x.NetBytesSentTotal
	}
	return 0
}

func (x *SystemMetricsResponse) GetDiskUsages() []*DiskUsage {
	if x != nil {
		return x.DiskUsages
	}
	return nil
}

func (x *SystemMetricsResponse) GetActiveWebsockets() int32 {
	if x != nil {
		return x.ActiveWebsockets
	}
	return 0
}

func (x *SystemMetricsResponse) GetGoroutineCount() int32 {
	if x != nil {
		return x.GoroutineCount
	}
	return 0
}

func (x *SystemMetricsResponse) GetDbStats() *DBStats {
	if x != nil {
		return x.DbStats
	}
	return nil
}

func (x *SystemMetricsResponse) GetAppUptime() string {
	if x != nil {
		return x.AppUptime
	}
	return ""
}

func (x *SystemMetricsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SystemMetricsResponse) GetCacheAge() *durationpb.Duration {
	if x != nil {
		return x.CacheAge
	}
	return nil
}

func (x *SystemMetricsResponse) GetApiMetrics() *ApiMetrics {
	if x != nil {
		return x.ApiMetrics
	}
	return nil
}

var File_middlewares_proto_health_proto protoreflect.FileDescriptor

const file_middlewares_proto_health_proto_rawDesc = "" +
	"\n" +
	"\x1emiddlewares/proto/health.proto\x12\x0egrpc.health.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xb1\x01\n" +
	"\x13HealthCheckResponse\x12I\n" +
	"\x06status\x18\x01 \x01(\x0e21.grpc.health.v1.HealthCheckResponse.ServingStatusR\x06status\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x03\"b\n" +
	"\x14SystemMetricsRequest\x12!\n" +
	"\finclude_disk\x18\x01 \x01(\bR\vincludeDisk\x12'\n" +
	"\x0finclude_network\x18\x02 \x01(\bR\x0eincludeNetwork\"x\n" +
	"\tDiskUsage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x04R\atotalMb\x12\x17\n" +
	"\aused_mb\x18\x03 \x01(\x04R\x06usedMb\x12#\n" +
	"\rusage_percent\x18\x04 \x01(\x01R\fusagePercent\"y\n" +
	"\aDBStats\x12$\n" +
	"\x0emax_open_conns\x18\x01 \x01(\x05R\fmaxOpenConns\x12\x1d\n" +
	"\n" +
	"open_conns\x18\x02 \x01(\x05R\topenConns\x12\x15\n" +
	"\x06in_use\x18\x03 \x01(\x05R\x05inUse\x12\x12\n" +
	"\x04idle\x18\x04 \x01(\x05R\x04idle\"\x8c\x03\n" +
	"\n" +
	"ApiMetrics\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x02 \x01(\x03R\vtotalErrors\x12,\n" +
	"\x12error_rate_percent\x18\x03 \x01(\tR\x10errorRatePercent\x120\n" +
	"\x14success_rate_percent\x18\x04 \x01(\tR\x12successRatePercent\x12/\n" +
	"\x14avg_response_time_ms\x18\x05 \x01(\x01R\x11avgResponseTimeMs\x12^\n" +
	"\x12requests_by_method\x18\x06 \x03(\v20.grpc.health.v1.ApiMetrics.RequestsByMethodEntryR\x10requestsByMethod\x1aC\n" +
	"\x15RequestsByMethodEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xdd\x05\n" +
	"\x15SystemMetricsResponse\x12,\n" +
	"\x12system_uptime_secs\x18\x01 \x01(\x04R\x10systemUptimeSecs\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x01R\x0fcpuUsagePercent\x12 \n" +
	"\fram_total_mb\x18\x03 \x01(\x04R\n" +
	"ramTotalMb\x12\x1e\n" +
	"\vram_used_mb\x18\x04 \x01(\x04R\tramUsedMb\x12*\n" +
	"\x11ram_usage_percent\x18\x05 \x01(\x01R\x0framUsagePercent\x127\n" +
	"\x18net_bytes_received_total\x18\x06 \x01(\x04R\x15netBytesReceivedTotal\x12/\n" +
	"\x14net_bytes_sent_total\x18\a \x01(\x04R\x11netBytesSentTotal\x12:\n" +
	"\vdisk_usages\x18\b \x03(\v2\x19.grpc.health.v1.DiskUsageR\n" +
	"diskUsages\x12+\n" +
	"\x11active_websockets\x18\t \x01(\x05R\x10activeWebsockets\x12'\n" +
	"\x0fgoroutine_count\x18\n" +
	" \x01(\x05R\x0egoroutineCount\x122\n" +
	"\bdb_stats\x18\v \x01(\v2\x17.grpc.health.v1.DBStatsR\adbStats\x12\x1d\n" +
	"\n" +
	"app_uptime\x18\f \x01(\tR\tappUptime\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x126\n" +
	"\tcache_age\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\bcacheAge\x12;\n" +
	"\vapi_metrics\x18\x0f \x01(\v2\x1a.grpc.health.v1.ApiMetricsR\n" +
	"apiMetrics2\xf4\x02\n" +
	"\x06Health\x12P\n" +
	"\x05Check\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.health.v1.HealthCheckResponse\x12R\n" +
	"\x05Watch\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.health.v1.HealthCheckResponse0\x01\x12_\n" +
	"\x10GetSystemMetrics\x12$.grpc.health.v1.SystemMetricsRequest\x1a%.grpc.health.v1.SystemMetricsResponse\x12c\n" +
	"\x12WatchSystemMetrics\x12$.grpc.health.v1.SystemMetricsRequest\x1a%.grpc.health.v1.SystemMetricsResponse0\x01B\"Z devtv/middlewares/proto/healthpbb\x06proto3"

var (
	file_middlewares_proto_health_proto_rawDescOnce sync.Once
	file_middlewares_proto_health_proto_rawDescData []byte
)

func file_middlewares_proto_health_proto_rawDescGZIP() []byte {
	file_middlewares_proto_health_proto_rawDescOnce.Do(func() {
		file_middlewares_proto_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_middlewares_proto_health_proto_rawDesc), len(file_middlewares_proto_health_proto_rawDesc)))
	})
	return file_middlewares_proto_health_proto_rawDescData
}

var file_middlewares_proto_health_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_middlewares_proto_health_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_middlewares_proto_health_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: grpc.health.v1.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 1: grpc.health.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: grpc.health.v1.HealthCheckResponse
	(*SystemMetricsRequest)(nil),           // 3: grpc.health.v1.SystemMetricsRequest
	(*DiskUsage)(nil),                      // 4: grpc.health.v1.DiskUsage
	(*DBStats)(nil),                        // 5: grpc.health.v1.DBStats
	(*ApiMetrics)(nil),                     // 6: grpc.health.v1.ApiMetrics
	(*SystemMetricsResponse)(nil),          // 7: grpc.health.v1.SystemMetricsResponse
	nil,                                    // 8: grpc.health.v1.ApiMetrics.RequestsByMethodEntry
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),            // 10: google.protobuf.Duration
}
var file_middlewares_proto_health_proto_depIdxs = []int32{
	0,  // 0: grpc.health.v1.HealthCheckResponse.status:type_name -> grpc.health.v1.HealthCheckResponse.ServingStatus
	8,  // 1: grpc.health.v1.ApiMetrics.requests_by_method:type_name -> grpc.health.v1.ApiMetrics.RequestsByMethodEntry
	4,  // 2: grpc.health.v1.SystemMetricsResponse.disk_usages:type_name -> grpc.health.v1.DiskUsage
	5,  // 3: grpc.health.v1.SystemMetricsResponse.db_stats:type_name -> grpc.health.v1.DBStats
	9,  // 4: grpc.health.v1.SystemMetricsResponse.timestamp:type_name -> google.protobuf.Timestamp
	10, // 5: grpc.health.v1.SystemMetricsResponse.cache_age:type_name -> google.protobuf.Duration
	6,  // 6: grpc.health.v1.SystemMetricsResponse.api_metrics:type_name -> grpc.health.v1.ApiMetrics
	1,  // 7: grpc.health.v1.Health.Check:input_type -> grpc.health.v1.HealthCheckRequest
	1,  // 8: grpc.health.v1.Health.Watch:input_type -> grpc.health.v1.HealthCheckRequest
	3,  // 9: grpc.health.v1.Health.GetSystemMetrics:input_type -> grpc.health.v1.SystemMetricsRequest
	3,  // 10: grpc.health.v1.Health.WatchSystemMetrics:input_type -> grpc.health.v1.SystemMetricsRequest
	2,  // 11: grpc.health.v1.Health.Check:output_type -> grpc.health.v1.HealthCheckResponse
	2,  // 12: grpc.health.v1.Health.Watch:output_type -> grpc.health.v1.HealthCheckResponse
	7,  // 13: grpc.health.v1.Health.GetSystemMetrics:output_type -> grpc.health.v1.SystemMetricsResponse
	7,  // 14: grpc.health.v1.Health.WatchSystemMetrics:output_type -> grpc.health.v1.SystemMetricsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_middlewares_proto_health_proto_init() }
func file_middlewares_proto_health_proto_init() {
	if File_middlewares_proto_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_middlewares_proto_health_proto_rawDesc), len(file_middlewares_proto_health_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_middlewares_proto_health_proto_goTypes,
		DependencyIndexes: file_middlewares_proto_health_proto_depIdxs,
		EnumInfos:         file_middlewares_proto_health_proto_enumTypes,
		MessageInfos:      file_middlewares_proto_health_proto_msgTypes,
	}.Build()
	File_middlewares_proto_health_proto = out.File
	file_middlewares_proto_health_proto_goTypes = nil
	file_middlewares_proto_health_proto_depIdxs = nil
}
